# fly.toml app configuration file generated for chargebeacon-web on 2024-02-05T20:11:36-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chargebeacon-web'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
