import "./globals.css";
import Navbar from "@/components/navbar";
import BeaconMap from "@/components/map/beacon-map";

export const metadata = {
    title: "ChargeBeacon Map",
    description: "Generated by create next app",
};

export default function HomeLayout({children}) {
    return (
        <html lang="en">
            <body>
                <Navbar/>
                <BeaconMap children={children}/>
            </body>
        </html>
    );
}
